# Generated by Django 5.0.3 on 2024-04-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('artifact_type', models.CharField(choices=[('CORREDIZA', 'Corrediza'), ('FIJA', 'Fija'), ('BATIENTE', 'Batiente'), ('PROYECTANTE', 'Proyectante'), ('DESLIZANTE', 'Deslizante')], max_length=20)),
                ('design', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AlumLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'Lineas',
            },
        ),
        migrations.CreateModel(
            name='AlumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('optional_code', models.CharField(max_length=20, unique=True)),
                ('length', models.FloatField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='AlumArtifactPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=0)),
                ('amount_panel', models.IntegerField(default=0)),
                ('panel_type', models.CharField(choices=[('CORREDIZA', 'Corrediza'), ('FIJA', 'Fija'), ('BATIENTE', 'Batiente'), ('PROYECTANTE', 'Proyectante'), ('DESLIZANTE', 'Deslizante')], max_length=20)),
                ('artifact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='main_app.alumartifact')),
            ],
        ),
        migrations.CreateModel(
            name='AlumPanelSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('artifact_panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.alumartifactpanel')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.alumsection')),
            ],
        ),
        migrations.CreateModel(
            name='AlumSectionMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('milimeter', models.FloatField(default=0)),
                ('inch', models.FloatField(default=0)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.alumsection')),
            ],
        ),
        migrations.CreateModel(
            name='AlumSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='main_app.alumline')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.CreateModel(
            name='AlumSectionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_item', models.TextField()),
                ('conect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.alumsystem')),
            ],
        ),
        migrations.AddField(
            model_name='alumsection',
            name='system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main_app.alumsystem'),
        ),
        migrations.CreateModel(
            name='AlumLineDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_item', models.TextField()),
                ('conect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.alumsystem')),
            ],
        ),
        migrations.AddField(
            model_name='alumartifact',
            name='system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='main_app.alumsystem'),
        ),
        migrations.CreateModel(
            name='AlumSystemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_item', models.TextField()),
                ('system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='main_app.alumsystem')),
            ],
        ),
    ]
