# Generated by Django 5.0.3 on 2024-04-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumartifactpanel',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alumartifactpanel',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
