# Generated by Django 5.0.3 on 2024-07-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alumartifactpanel_height_alumartifactpanel_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumartifact',
            name='has_alfajia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumartifact',
            name='has_parche',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumartifactpanel',
            name='panel_type',
            field=models.CharField(choices=[('MOVIL', 'Móvil'), ('FIJO', 'Fijo'), ('BATIENTE', 'Batiente'), ('PROYECTANTE', 'Proyectante'), ('DESLIZANTE', 'Deslizante'), ('MARCO', 'Marco')], max_length=20),
        ),
    ]
