# Generated by Django 5.0.3 on 2024-07-05 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alumartifact_has_alfajia_alumartifact_has_parche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumsectiondescription',
            name='conect_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='main_app.alumsection'),
        ),
    ]
