# Generated by Django 5.0.3 on 2024-07-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_alumsectiondescription_conect_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumartifact',
            name='design',
            field=models.CharField(default='O', max_length=10),
        ),
    ]
