# Generated by Django 5.0.3 on 2024-07-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_alumartifact_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumartifact',
            name='has_adapter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumartifactpanel',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alumartifact',
            name='design',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alumartifactpanel',
            name='panel_type',
            field=models.CharField(choices=[('MOVIL', 'Móvil'), ('FIJO', 'Fijo'), ('PARCHE', 'Parche'), ('BATIENTE', 'Batiente'), ('PROYECTANTE', 'Proyectante'), ('DESLIZANTE', 'Deslizante'), ('MARCO', 'Marco')], max_length=20),
        ),
    ]
