# Generated by Django 5.0.3 on 2024-07-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alumartifact_has_adapter_alumartifactpanel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumpanelsection',
            name='artifact_panel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main_app.alumartifactpanel'),
        ),
    ]
