# Generated by Django 5.0.3 on 2024-07-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_alumpanelsection_artifact_panel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumpanelsection',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
