ALUM_SYSTEMS_LIST_SLIDING = ['3825','5020','744','8025','7038']
ALUM_SYSTEMS_LIST_PROJECTOR = []
ALUM_SYSTEMS_LIST_SWING = []

#LETTERS_TYPES_LIST['X':'MOVIL', 'O':'FIJA, 'B':'BATIENTE', 'P':'PROYECTANTE', 'D':'DESLIZANTE', 'M':'MARCO' ]
LETTERS_TYPES_LIST=['X', 'O', 'B', 'P', 'D', 'M' ]

#LETTERS_TYPES_SLIDING['X':'MOVIL', 'O':'FIJA, 'P':'PARCHE' ]
LETTERS_TYPES_SLIDING = ['X', 'O', 'P', 'M']
#DESIGN_TYPES_5020['OX','XO','XX','OXO','PXX','XXP','OXXO']
DESIGN_TYPES_5020=['OX','XO','XX','OXO','XOX','PXX','XXP','OXXO']

